import type { Experience } from "./types";

export const experiences: Experience[] = [
  {
    id: "temas",
    role: "Full Stack Software Developer",
    company: "PT Temas Tbk",
    location: "Jakarta, Indonesia",
    period: "Feb 2025 - Feb 2026",
    description: [
      "Shipped 4 production systems used daily by 100+ IT staff across Enterprise IT divisions. Delivered end-to-end from requirements → design → implementation → production monitoring.",
      "TIMES Service Desk: Built enterprise ticketing platform with dynamic approval workflows (LOA), handling 100+ tickets/day. Implemented complete audit trail for compliance. Tech: Go/Fiber, Vue.js/Quasar, PostgreSQL.",
      "Warehouse Management System (WMS): Enhanced data validation and search performance. Reduced validation failures by 70% and improved query speed 2.5x. Implemented brand/commodity tagging and complex SQL constraints.",
      "Core Module: Architected single source of truth for master data (containers, trucks, cargo, document fees) to support company-wide invoicing system migration.",
      "Training Hub (Maritime): Built schedule management system with automated notifications and prerequisite tracking. Manages 500+ maritime personnel certifications.",
      "Full deployment ownership: Managed SIT → UAT → PROD pipelines using Jenkins CI/CD on self-managed infrastructure. Implemented atomic deployments with zero-downtime rollouts.",
      "Backend expertise: Designed RESTful APIs in Go (Fiber) with performance optimization, connection pooling, and caching strategies.",
      "Frontend: Built responsive interfaces with Vue.js (Quasar), complex state management, and real-time component updates.",
      "Database: Advanced PostgreSQL work including query optimization, complex data modeling for approval workflows, and backup automation.",
      "Agile practices: Daily standups, sprint planning, retrospectives, code reviews, pair programming. Collaborated with 5+ engineers and product teams.",
    ],
    techStack: [
      "Go (Fiber)",
      "Vue.js (Quasar)",
      "PostgreSQL",
      "Redis",
      "MinIO",
      "Jenkins CI/CD",
      "RESTful APIs",
      "System Architecture",
      "Agile/Scrum",
    ],
  },
  {
    id: "vihara-dhamma-ratna",
    role: "Public Relations & Event Organizer",
    company: "Nobel Vihara Dhamma Ratna (VDR Youth)",
    location: "Tangerang, Indonesia",
    period: "Present",
    description: [
      "Manage public relations and communication strategies for the organization.",
      "Spearhead event organizing and material preparation, including acting as the head of the committee for the VDR Youth 11th-anniversary talkshow, 'i11UMINATE'.",
    ],
    techStack: [
      "Public Relations",
      "Event Management",
      "Team Leadership",
      "Communication",
    ],
  },
  {
    id: "teach-for-indonesia",
    role: "Volunteer - Save The Ocean",
    company: "Teach For Indonesia, BINUS University",
    location: "Indonesia",
    period: "2024",
    description: [
      "Participated in the 'Save The Ocean' coastal cleanup initiative focused on creating a positive social and environmental impact.",
      "Collaborated with a team to successfully accumulate and properly dispose of over 150+ kilograms of garbage from Indonesian coasts.",
    ],
    techStack: [
      "Community Service",
      "Teamwork",
      "Environmental Sustainability",
    ],
  },
  {
    id: "himti-binus",
    role: "Active Member",
    company: "HIMTI BINUS University",
    location: "Jakarta, Indonesia",
    period: "Nov 2022 - Jan 2024",
    description: [
      "Actively participated in the Computer Science Student Association (HIMTI) programs and initiatives.",
      "Collaborated with peers to support technology-focused events and community building within the university.",
    ],
    techStack: ["Organization", "Collaboration", "Networking"],
  },
  {
    id: "jagad-jaya",
    role: "Sales Promotion (PRJ Event)",
    company: "PT. Jagad Jaya Luggassindo",
    location: "Jakarta, Indonesia",
    period: "Jun 2022 - Jul 2022",
    description: [
      "Represented the company during the fast-paced Jakarta Fair (PRJ) sales event.",
      "Achieved the highest selling record in the Home and Appliances Category through effective product promotion and customer engagement.",
    ],
    techStack: ["Direct Sales", "Customer Communication", "Marketing"],
  },
  {
    id: "akukatsoe",
    role: "Co-Founder",
    company: "AkuKatsoe",
    location: "Tangerang, Indonesia",
    period: "2021 - Present",
    description: [
      "Co-founded and managed a fast-growing Japanese food (Katsu) culinary business.",
      "Successfully served around 600 Katsu Boxes, with 70% of orders catering to large parties and events.",
      "Handled product development, marketing (IG: @akukatsoe), and daily business operations.",
    ],
    techStack: [
      "Entrepreneurship",
      "Business Management",
      "Marketing",
      "F&B Operations",
    ],
  },
];
